// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations run over a DIRECT (non-pooled) connection — Prisma's migration
    // engine needs a real session (advisory locks, DDL), which a PgBouncer pool
    // can't provide. Falls back to DATABASE_URL when DIRECT_URL is unset (e.g.
    // local Docker, which has no separate pooled endpoint).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
