-- Government contribution rates effective 2025-01-01
-- SSS: RA 11199 schedule — 15% total (5% employee, 10% employer)
--   Monthly Salary Credit (MSC) ranges ₱5,000–₱35,000 in ₱500 steps.
-- PhilHealth: 5% premium, split equally; floor ₱10,000, ceiling ₱100,000.
--
-- To update rates: create a new migration with a later effective_date batch.
-- Do NOT edit this file — historical payroll runs reference these rows.

-- SSS brackets
INSERT INTO statutory_sss_brackets
  (id, effective_date, min_salary, max_salary, monthly_credit, employee_share, employer_share, created_at)
VALUES
  (gen_random_uuid(), '2025-01-01', 0,         5249.99,    5000,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 5250,       5749.99,    5500,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 5750,       6249.99,    6000,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 6250,       6749.99,    6500,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 6750,       7249.99,    7000,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 7250,       7749.99,    7500,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 7750,       8249.99,    8000,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 8250,       8749.99,    8500,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 8750,       9249.99,    9000,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 9250,       9749.99,    9500,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 9750,      10249.99,   10000,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 10250,     10749.99,   10500,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 10750,     11249.99,   11000,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 11250,     11749.99,   11500,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 11750,     12249.99,   12000,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 12250,     12749.99,   12500,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 12750,     13249.99,   13000,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 13250,     13749.99,   13500,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 13750,     14249.99,   14000,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 14250,     14749.99,   14500,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 14750,     15249.99,   15000,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 15250,     15749.99,   15500,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 15750,     16249.99,   16000,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 16250,     16749.99,   16500,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 16750,     17249.99,   17000,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 17250,     17749.99,   17500,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 17750,     18249.99,   18000,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 18250,     18749.99,   18500,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 18750,     19249.99,   19000,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 19250,     19749.99,   19500,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 19750,     20249.99,   20000,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 20250,     20749.99,   20500,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 20750,     21249.99,   21000,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 21250,     21749.99,   21500,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 21750,     22249.99,   22000,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 22250,     22749.99,   22500,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 22750,     23249.99,   23000,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 23250,     23749.99,   23500,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 23750,     24249.99,   24000,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 24250,     24749.99,   24500,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 24750,     25249.99,   25000,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 25250,     25749.99,   25500,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 25750,     26249.99,   26000,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 26250,     26749.99,   26500,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 26750,     27249.99,   27000,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 27250,     27749.99,   27500,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 27750,     28249.99,   28000,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 28250,     28749.99,   28500,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 28750,     29249.99,   29000,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 29250,     29749.99,   29500,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 29750,     30249.99,   30000,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 30250,     30749.99,   30500,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 30750,     31249.99,   31000,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 31250,     31749.99,   31500,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 31750,     32249.99,   32000,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 32250,     32749.99,   32500,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 32750,     33249.99,   33000,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 33250,     33749.99,   33500,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 33750,     34249.99,   34000,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 34250,     34749.99,   34500,  0.05, 0.10, NOW()),
  (gen_random_uuid(), '2025-01-01', 34750, 99999999.99,   35000,  0.05, 0.10, NOW());

-- PhilHealth bracket
INSERT INTO statutory_philhealth_brackets
  (id, effective_date, min_salary, max_salary, rate, min_contribution, max_contribution, created_at)
VALUES
  (gen_random_uuid(), '2025-01-01', 10000, 100000, 0.05, 500, 5000, NOW());
